/**
 * Every route the review tooling walks, in one place.
 *
 * capture.mjs and mobile.mjs both read this. Two lists would drift, and the one that drifted
 * would be the one that stopped covering the screen that broke.
 */
export const ROUTES = [
  // Marketing — spec 5.1
  { name: 'home', path: '#/' },
  { name: 'hosting-shared', path: '#/hosting/shared' },
  { name: 'hosting-wordpress', path: '#/hosting/wordpress' },
  { name: 'hosting-cloud', path: '#/hosting/cloud' },
  { name: 'hosting-vps', path: '#/hosting/vps' },
  { name: 'hosting-email', path: '#/hosting/email' },
  { name: 'hosting-monitoring', path: '#/hosting/monitoring' },
  { name: 'ssl', path: '#/ssl' },
  { name: 'builder', path: '#/builder' },
  { name: 'domains', path: '#/domains' },
  { name: 'transfer', path: '#/transfer' },

  // Ordering — spec 5.2 and 7
  { name: 'configure', path: '#/configure/ultra' },
  { name: 'cart', path: '#/cart' },
  { name: 'checkout', path: '#/checkout' },
  { name: 'confirmation', path: '#/confirmation' },

  // Auth — spec 5.3 and 8
  { name: 'login', path: '#/login' },
  { name: 'register', path: '#/register' },
  { name: 'reset', path: '#/reset' },
  { name: 'twofactor', path: '#/2fa' },

  // Client area — spec 5.4 and 9
  { name: 'account', path: '#/account' },
  { name: 'acc-services', path: '#/account/services' },
  { name: 'acc-service', path: '#/account/services/svc-8841' },
  { name: 'acc-domains', path: '#/account/domains' },
  { name: 'acc-domain', path: '#/account/domains/dom-1' },
  { name: 'acc-invoices', path: '#/account/invoices' },
  { name: 'acc-invoice', path: '#/account/invoices/inv-4417' },
  { name: 'acc-funds', path: '#/account/funds' },
  { name: 'acc-payment-methods', path: '#/account/payment-methods' },
  { name: 'acc-tickets', path: '#/account/tickets' },
  { name: 'acc-ticket-new', path: '#/account/tickets/new' },
  { name: 'acc-ticket', path: '#/account/tickets/tkt-7741' },
  { name: 'acc-kb', path: '#/account/knowledgebase' },
  { name: 'acc-kb-article', path: '#/account/knowledgebase/point-domain' },
  { name: 'acc-announcements', path: '#/account/announcements' },
  { name: 'acc-affiliates', path: '#/account/affiliates' },
  { name: 'acc-contacts', path: '#/account/contacts' },
  { name: 'acc-security', path: '#/account/security' },
  { name: 'acc-upgrade', path: '#/account/services/svc-8841/upgrade' },
  { name: 'acc-upgrade-review', path: '#/account/services/svc-8841/upgrade/review?to=unlimited' },
  { name: 'acc-upgrade-done', path: '#/account/services/svc-8841/upgrade/done?to=unlimited' },
  { name: 'acc-cancel', path: '#/account/services/svc-8841/cancel' },
  { name: 'acc-renew', path: '#/account/renew/svc-8841' },
  { name: 'acc-transactions', path: '#/account/transactions' },
  { name: 'acc-payment-failed', path: '#/account/payment-failed' },
  { name: 'acc-withdraw', path: '#/account/affiliates/withdraw' },
  { name: 'acc-notifications', path: '#/account/notifications' },
  { name: 'compare', path: '#/compare' },
  { name: 'product', path: '#/product/ultra' },
  { name: 'tld-pricing', path: '#/domains/pricing' },
  { name: 'migrate', path: '#/migrate' },
  { name: 'status', path: '#/status' },
  { name: 'about', path: '#/about' },
  { name: 'data-centres', path: '#/data-centres' },
  { name: 'contact', path: '#/contact' },
  { name: 'learn', path: '#/learn' },
  { name: 'learn-post', path: '#/learn/move-a-site' },
  { name: 'registrant', path: '#/checkout/registrant' },
  { name: 'card-entry', path: '#/checkout/card' },
  { name: '3ds-go', path: '#/checkout/3ds' },
  { name: '3ds-back', path: '#/checkout/3ds?state=return' },
  { name: 'bank-transfer', path: '#/order/bank' },
  { name: 'wallet-transfer', path: '#/order/wallet' },
  { name: 'payment-failed-order', path: '#/order/failed' },
  { name: 'order-pending', path: '#/order/pending' },
  { name: 'set-password', path: '#/reset/new' },
  { name: 'verify-email', path: '#/verify' },
  { name: 'verify-done', path: '#/verify?state=done' },
  { name: 'session-expired', path: '#/expired' },
  { name: 'err-404', path: '#/error/404' },
  { name: 'err-500', path: '#/error/500' },
  { name: 'err-403', path: '#/error/403' },
  { name: 'err-maintenance', path: '#/error/maintenance' },
  { name: 'cpanel-sso', path: '#/cpanel' },
  { name: 'sys-banners', path: '#/system/banners' },
  { name: 'not-found', path: '#/no/such/page' },

  { name: 'legal', path: '#/legal/privacy' },
];
